mutation AddStudent($data: NewStudentInput!) {
    addStudent(data: $data) {
        id
        firstname
        lastname
        email
        telephone
        avatar
        class {
            id
        }
    }
}