query GetAllStudents {
    getAllStudents {
        id
        lastname
        firstname
        email
        telephone
        avatar
        class {
            id
            name
            year
        }
    }
}